services:
  pg:
    image: postgres:16.6
    networks:
      - app-network
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data:Z
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: pg
      POSTGRES_DB: studs
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file:
      - .env

volumes:
  pg-data:

networks:
  app-network:
    driver: bridge
